// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicSugessionAppMVP_ASP.Persistance;

#nullable disable

namespace MusicSugessionAppMVP_ASP.Migrations
{
    [DbContext(typeof(Persistence))]
    [Migration("20260112181735_migration2")]
    partial class migration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeezerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusicBrainzId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SpotifyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.ArtistExposure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExposedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SessionId");

                    b.ToTable("ArtistExposures");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.ArtistNoSimilarFound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecordedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("ArtistNoSimilarFounds");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.ArtistSimilarityApi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SimilarArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ArtistSimilarityApis");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.ArtistSimilarityInternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SimilarArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ArtistSimilarityInternals");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.GenreExposure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExposedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("SessionId");

                    b.ToTable("GenreExposures");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DeviceType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SessionExport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Medium")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionExports");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SessionInputArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SessionId");

                    b.ToTable("SessionInputArtists");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SessionStats", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("TotalSwipes")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.ToTable("SessionStats");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SessionStatsSnapshot", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dislikes")
                        .HasColumnType("int");

                    b.Property<int>("Likes")
                        .HasColumnType("int");

                    b.Property<int>("TotalSwipes")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "CapturedAtUtc");

                    b.ToTable("SessionStatsSnapshots");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.StreamingPlatform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StreamingPlatforms");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SwipeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SwipedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TrackId");

                    b.ToTable("SwipeEvents");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.TrackExposure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExposedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("TrackId");

                    b.ToTable("TrackExposures");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TrackGenres");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.TrackStats", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalDislikes")
                        .HasColumnType("int");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("int");

                    b.HasKey("TrackId");

                    b.ToTable("TrackStats");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PreferredStreamingPlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PreferredStreamingPlatformId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.UserRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.ArtistExposure", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.ArtistNoSimilarFound", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.GenreExposure", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Session", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SessionExport", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SessionInputArtist", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Session", "Session")
                        .WithMany("InputArtists")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.SwipeEvent", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Session", "Session")
                        .WithMany("SwipeEvents")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Track", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.TrackExposure", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.TrackGenre", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Genre", "Genre")
                        .WithMany("Tracks")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.Track", "Track")
                        .WithMany("Genres")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.User", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.StreamingPlatform", "PreferredStreamingPlatform")
                        .WithMany()
                        .HasForeignKey("PreferredStreamingPlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreferredStreamingPlatform");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.UserRoleAssignment", b =>
                {
                    b.HasOne("MusicSugessionAppMVP_ASP.Persistance.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Genre", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Session", b =>
                {
                    b.Navigation("InputArtists");

                    b.Navigation("SwipeEvents");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.Track", b =>
                {
                    b.Navigation("Genres");
                });

            modelBuilder.Entity("MusicSugessionAppMVP_ASP.Persistance.User", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
